version: "3"

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - .env
    volumes:
      - ./client:/client
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run start"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    volumes:
      - ./server:/server
      - /app/node_modules
    ports:
      - "3001:3000"
    command: >
      sh -c "npm install && npm run dev"
