version: "3"

services:
  mongodb:
    image: mongo:7.0.0
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - mern-app-network

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - .env
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run start"
    networks:
      - mern-app-network

  server:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    volumes:
      - ./server:/server
    ports:
      - "3001:3000"
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - mern-app-network

volumes:
  mongodb_data:

networks:
  mern-app-network:
    driver: bridge
