version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    volumes:
      - ./server:/server
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run dev"
